name: Assignment Helper

on:
  issue_comment:
    types: [created]

permissions:
  issues: write

jobs:
  assignment-helper:
    uses: kubestellar/infra/.github/workflows/reusable-assignment-helper.yml@2cdb7c22649c4e5cd36edc2d2fc57de96949e7a9 # main
