name: Copilot DCO

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  copilot-dco:
    uses: kubestellar/infra/.github/workflows/reusable-copilot-dco.yml@2cdb7c22649c4e5cd36edc2d2fc57de96949e7a9 # main
