name: Label Helper

on:
  issue_comment:
    types: [created]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  label-helper:
    uses: kubestellar/infra/.github/workflows/reusable-label-helper.yml@2cdb7c22649c4e5cd36edc2d2fc57de96949e7a9 # main
