name: PR Verifier

on:
  pull_request_target:
    types: [opened, edited, synchronize, reopened]

permissions:
  checks: write
  pull-requests: read
  packages: read

jobs:
  verify:
    uses: kubestellar/infra/.github/workflows/reusable-pr-verifier.yml@2cdb7c22649c4e5cd36edc2d2fc57de96949e7a9 # main
