name: "PR Title Verifier"

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  verify:
    uses: kubestellar/infra/.github/workflows/reusable-pr-verify-title.yml@2cdb7c22649c4e5cd36edc2d2fc57de96949e7a9 # main
