name: OpenSSF Scorecard

on:
  schedule:
    - cron: '0 6 * * 1'
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  security-events: write
  contents: read
  actions: read
  id-token: write

jobs:
  analysis:
    uses: kubestellar/infra/.github/workflows/reusable-scorecard.yml@2cdb7c22649c4e5cd36edc2d2fc57de96949e7a9 # main
