name: Stale Issues

on:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight UTC
  workflow_dispatch:

permissions:
  issues: write

jobs:
  stale:
    uses: kubestellar/infra/.github/workflows/reusable-stale.yml@2cdb7c22649c4e5cd36edc2d2fc57de96949e7a9 # main
